//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocCtrlX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_tran
    {
        public string doc_no { get; set; }
        public int org { get; set; }
        public byte lv_id { get; set; }
        public int status_id { get; set; }
        public string action_id { get; set; }
        public System.DateTime act_dt { get; set; }
        public string comment { get; set; }
    
        public virtual td_doc td_doc { get; set; }
        public virtual tm_level tm_level { get; set; }
    }
}
