//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocCtrlX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_doc_type
    {
        public tm_doc_type()
        {
            this.td_doc = new HashSet<td_doc>();
        }
    
        public byte doc_type_id { get; set; }
        public string doc_type_name { get; set; }
    
        public virtual ICollection<td_doc> td_doc { get; set; }
    }
}
