//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocCtrlX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_level
    {
        public tm_level()
        {
            this.td_tran = new HashSet<td_tran>();
        }
    
        public byte lv_id { get; set; }
        public string lv_name { get; set; }
        public Nullable<byte> pos_min { get; set; }
        public Nullable<byte> pos_max { get; set; }
    
        public virtual ICollection<td_tran> td_tran { get; set; }
    }
}
